#!/usr/bin/perl

if ($#ARGV < 0) {
	print STDERR "Usage: $0 bound\n";
	exit(EXIT_FAILURE);
}

$bound = $ARGV[0];

system "cat ../data/locationstream-2013*list | ../limit-specified ../bounds/$bound | /data2/data/github/geotools/cleanse -u | awk '{print \$1, \$2, \$3, \$4 }' | tee /tmp/$bound.list | ../plot-motion | head -100000 > /tmp/$bound.geo";

$lines = 0;
open(IN, "/tmp/$bound.list");
while (<IN>) {
	$lines++;
}
close(IN);

$seq = 0;
open(IN, "cat /tmp/$bound.geo | ./normalize-geo-specified ../bounds/$bound |");
while (<IN>) {
	if ($seq % 25 == 0) {
		close(OUT);

		srand($seq);
		open(TMP, ">/tmp/$$");
		open(LIST, "/tmp/$bound.list");
		$count = 0;
		while (<LIST>) {
			if (rand(1) < 10000 / $lines) {
				print TMP $_;
				$count++;
			}
		}
		close(LIST);
		close(TMP);
		# print STDERR "$count\n";

		open(OUT, "| (cat /tmp/$$ | ./normalize-list-specified ../bounds/$bound | ./voronoi/voronoi -t; cat) | ./route");
	}

	$seq++;
	print OUT;

	last if ($seq > 10000);
}
close(IN);
